// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omlritdgeoqmvlzwgyyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tbHJpdGRnZW9xbXZsendneXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODE2MzEsImV4cCI6MjA2MDA1NzYzMX0.RQ1ttJEq3LL6t1WQ4igj8LZC-egAjpN7PrBYjBJeKxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);